import type { TerminalConfig } from '../../types/config';
import { themes } from '../themes';

export function generateGhosttyConfig(config: TerminalConfig): string {
  const { appearance, font, window, cursor, shell, advanced } = config;
  const themeColors = themes[appearance.theme].colors;
  const colors = appearance.customColors || themeColors;

  let configText = `# Ghostty Configuration File
# Generated by Terminal Config Generator

# Font
font-family = ${font.family}
font-size = ${font.size}
font-weight = ${font.weight}
font-variant = ${font.ligatures ? 'ligatures' : 'no-ligatures'}

# Colors
foreground = ${colors.foreground}
background = ${colors.background}
cursor-color = ${cursor.color}

# Normal colors
color0 = ${colors.black}
color1 = ${colors.red}
color2 = ${colors.green}
color3 = ${colors.yellow}
color4 = ${colors.blue}
color5 = ${colors.magenta}
color6 = ${colors.cyan}
color7 = ${colors.white}

# Bright colors
color8 = ${colors.brightBlack}
color9 = ${colors.brightRed}
color10 = ${colors.brightGreen}
color11 = ${colors.brightYellow}
color12 = ${colors.brightBlue}
color13 = ${colors.brightMagenta}
color14 = ${colors.brightCyan}
color15 = ${colors.brightWhite}

# Window
window-width = ${window.width}c
window-height = ${window.height}r
window-padding-x = ${window.paddingX}
window-padding-y = ${window.paddingY}
window-opacity = ${appearance.opacity}
window-theme = ${window.decorations ? 'default' : 'none'}

# Cursor
cursor-style = ${cursor.style}
cursor-style-blink = ${cursor.blinking ? 'yes' : 'no'}

# Shell
command = ${shell.program}${shell.args.length > 0 ? ' ' + shell.args.join(' ') : ''}

# Scrollback
scrollback-limit = ${advanced.scrollbackSize}
clipboard-paste-protection = ${advanced.copyOnSelect ? 'true' : 'false'}

# Bell
audible-bell = ${advanced.audibleBell ? 'true' : 'false'}

`;

  return configText;
}
