import type { TerminalConfig } from '../../types/config';
import { themes } from '../themes';

export function generateKittyConfig(config: TerminalConfig): string {
  const { appearance, font, window, cursor, shell, advanced } = config;
  const themeColors = themes[appearance.theme].colors;
  const colors = appearance.customColors || themeColors;

  let configText = `# Kitty Configuration File
# Generated by Terminal Config Generator

# Font
font_family ${font.family}
font_size ${font.size}
${font.ligatures ? 'font_features ${font.family} +calt +liga' : '# font_features disabled'}

# Colors
foreground ${colors.foreground}
background ${colors.background}
cursor ${cursor.color}

# Normal colors
color0 ${colors.black}
color1 ${colors.red}
color2 ${colors.green}
color3 ${colors.yellow}
color4 ${colors.blue}
color5 ${colors.magenta}
color6 ${colors.cyan}
color7 ${colors.white}

# Bright colors
color8 ${colors.brightBlack}
color9 ${colors.brightRed}
color10 ${colors.brightGreen}
color11 ${colors.brightYellow}
color12 ${colors.brightBlue}
color13 ${colors.brightMagenta}
color14 ${colors.brightCyan}
color15 ${colors.brightWhite}

# Window
remember_window_size no
initial_window_width ${window.width}c
initial_window_height ${window.height}r
window_padding_width ${window.paddingX}
window_padding_height ${window.paddingY}
background_opacity ${appearance.opacity}
dynamic_background_opacity yes

# Cursor
cursor_shape ${cursor.style}
cursor_blink_interval ${cursor.blinking ? (1000 / cursor.blinkRate).toFixed(1) : '0'}

# Shell
shell ${shell.program}${shell.args.length > 0 ? ' ' + shell.args.join(' ') : ''}

# Scrollback
scrollback_lines ${advanced.scrollbackSize}
copy_on_select ${advanced.copyOnSelect ? 'yes' : 'no'}

# Bell
enable_audio_bell ${advanced.audibleBell ? 'yes' : 'no'}

`;

  return configText;
}
